package com.remodelAi.Business_Manger.enums;
/*
public enum Vertical {
    ADVERTISING,
    AUTOMOTIVE,
    CONSUMER_PACKAGED_GOODS,
    ECOMMERCE,
    EDUCATION,
    ENERGY_AND_UTILITIES,
    ENTERTAINMENT_AND_MEDIA,
    FINANCIAL_SERVICES,
    GAMING,
    GOVERNMENT_AND_POLITICS,
    MARKETING,
    ORGANIZATIONS_AND_ASSOCIATIONS,
    PROFESSIONAL_SERVICES,
    RETAIL,
    TECHNOLOGY,
    TELECOM,
    TRAVEL,
    OTHER
}
*/